# Generated by Django 5.1.4 on 2026-02-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='universities/'),
        ),
    ]
